version: 0.0.1.{build}
image: Visual Studio 2017
shallow_clone: true

environment:
  matrix:
    - build_config: Debug
      build_target: 64_bit

    - build_config: Debug
      build_target: 32_bit

    - build_config: Release
      build_target: 64_bit

    - build_config: Release
      build_target: 32_bit

init:
  - if "%build_target%" == "64_bit" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - if "%build_target%" == "32_bit" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"

build_script:
  - C:\Python37\python build.py --cfg %build_config% -v

test: off

matrix:
  fast_finish: true
