"""Prepare the assets for a nanoprintf release. Publishing them is the caller's job.

The checked-in header carries a @NPF_VERSION@ placeholder where its version goes, so
nothing in the repository can go stale. This stamps a tag into it and writes, into --out:
the standalone header, a source bundle holding that same header, and release_notes.txt.
"""

import argparse
import pathlib
import re
import subprocess
import sys
import zipfile

_SCRIPT_PATH = pathlib.Path(__file__).resolve().parent
_HEADER = "nanoprintf.h"
_PLACEHOLDER = "@NPF_VERSION@"


def _parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser()
    parser.add_argument("--tag", help="Version tag to stamp into the header, e.g. v0.7.1")
    parser.add_argument("--repo", help="Repository to link and query, e.g. owner/nanoprintf")
    parser.add_argument(
        "--out",
        type=pathlib.Path,
        default=pathlib.Path("build/release"),
        help="Directory to write the assets into",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify the header still holds its version placeholder, then exit",
    )
    return parser.parse_args()


def _git(*args: str) -> str:
    """Run a git command in the repository and return its stdout."""
    return subprocess.run(
        ["git", *args], check=True, capture_output=True, text=True, cwd=_SCRIPT_PATH
    ).stdout


def _stamped_header(tag: str) -> bytes:
    """Return the header's bytes with its version placeholder replaced by the tag."""
    placeholder = _PLACEHOLDER.encode()
    data = (_SCRIPT_PATH / _HEADER).read_bytes()
    if placeholder not in data:
        msg = f"{_HEADER} has no {_PLACEHOLDER} placeholder to stamp"
        raise ValueError(msg)
    return data.replace(placeholder, tag.encode())


def _write_bundle(zip_path: pathlib.Path, prefix: str, header: bytes) -> None:
    """Zip every tracked file under prefix/, substituting the stamped header."""
    names = [n for n in _git("ls-files", "-z").split("\0") if n]
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as bundle:
        for name in sorted(names):
            src = _SCRIPT_PATH / name
            info = zipfile.ZipInfo.from_file(src, f"{prefix}/{name}")  # keeps the exec bit
            info.compress_type = zipfile.ZIP_DEFLATED
            bundle.writestr(info, header if name == _HEADER else src.read_bytes())


def _pr_title(repo: str, pr: str) -> str:
    """Look up a pull request title, empty if the number names no pull request.

    A number in a commit message can name an issue instead, which 404s. Every other
    failure -- a token without pull-requests read, a rate limit -- would quietly drop
    entries from the notes, so raise on those rather than publish a short changelog.
    """
    result = subprocess.run(
        ["gh", "api", f"repos/{repo}/pulls/{pr}", "--jq", ".title"],
        check=False,
        capture_output=True,
        text=True,
        cwd=_SCRIPT_PATH,
    )
    if result.returncode == 0:
        return result.stdout.strip()
    if "HTTP 404" in result.stderr:
        return ""
    msg = f"reading the title of pull request {pr} failed: {result.stderr.strip()}"
    raise RuntimeError(msg)


def _release_notes(tag: str, repo: str, zip_name: str) -> str:
    """Compose the notes: pull requests landed since the previous tag, then the assets."""
    lines = [f"nanoprintf {tag}:", ""]

    prev = [
        t
        for t in _git("tag", "--sort=-v:refname").split()
        if re.match(r"v[0-9]", t) and t != tag
    ]
    if prev:
        # A dry run names a tag that does not exist yet; walk to HEAD for it instead.
        exists = subprocess.run(
            ["git", "rev-parse", "--verify", "--quiet", f"refs/tags/{tag}"],
            check=False,
            capture_output=True,
            cwd=_SCRIPT_PATH,
        )
        log = _git("log", f"{prev[0]}..{tag if exists.returncode == 0 else 'HEAD'}", "--oneline")
        for pr in sorted(set(re.findall(r"\(#([0-9]+)\)", log)), key=int):
            title = _pr_title(repo, pr)
            if title:
                lines.append(f"{title} https://github.com/{repo}/pull/{pr}")
        lines.append("")

    lines += [
        f"`{_HEADER}`: the standalone header, stamped `{tag}`.",
        f"`{zip_name}`: full source, tests and examples included, same stamped header.",
        "",
        "The autogenerated source archives below carry an unstamped header, prefer the assets above.",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    """Stamp the header, then write the assets and the notes into the output directory."""
    args = _parse_args()

    if args.check:
        _stamped_header("checked")  # raises if the placeholder is gone
        return 0

    if not args.tag or not args.repo:
        print("--tag and --repo are required")
        return 1

    out = args.out if args.out.is_absolute() else _SCRIPT_PATH / args.out
    out.mkdir(parents=True, exist_ok=True)
    zip_name = f"nanoprintf-{args.tag}.zip"

    header = _stamped_header(args.tag)
    (out / _HEADER).write_bytes(header)
    _write_bundle(out / zip_name, f"nanoprintf-{args.tag}", header)
    notes = out / "release_notes.txt"
    notes.write_text(_release_notes(args.tag, args.repo, zip_name), encoding="utf-8")
    for asset in (out / _HEADER, out / zip_name, notes):
        print(asset)

    return 0


if __name__ == "__main__":
    sys.exit(main())
