# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  build-gcc-debug:
    docker:
      - image: charlesnicholson/circleci-images:latest
    steps:
      - checkout
      - run:
          command: |
            export CC=/usr/bin/gcc
            export CXX=/usr/bin/g++
            ./b Debug -v
  build-gcc-release:
    docker:
      - image: charlesnicholson/circleci-images:latest
    steps:
      - checkout
      - run:
          command: |
            export CC=/usr/bin/gcc
            export CXX=/usr/bin/g++
            ./b Release -v
  build-clang-debug:
    docker:
      - image: charlesnicholson/circleci-images:latest
    steps:
      - checkout
      - run:
          command: |
            export CC=/usr/bin/clang
            export CXX=/usr/bin/clang++
            ./b Debug -v
  build-clang-release:
    docker:
      - image: charlesnicholson/circleci-images:latest
    steps:
      - checkout
      - run:
          command: |
            export CC=/usr/bin/clang
            export CXX=/usr/bin/clang++
            ./b Release -v


workflows:
  submit-gate:
    jobs:
      - build-gcc-debug
      - build-gcc-release
      - build-clang-debug
      - build-clang-release
