version: 2.1

jobs:
  build-gcc-debug:
    docker:
      - image: charlesnicholson/circleci-images:latest
    environment:
      CC: /usr/bin/gcc
      CXX: /usr/bin/g++
    steps:
      - checkout
      - run:
          command: ./b --cfg Debug -v

  build-gcc-release:
    docker:
      - image: charlesnicholson/circleci-images:latest
    environment:
      CC: /usr/bin/gcc
      CXX: /usr/bin/g++
    steps:
      - checkout
      - run:
          command: ./b --cfg Release -v

  build-gcc-32-debug:
    docker:
      - image: charlesnicholson/circleci-images:latest
    environment:
      CC: /usr/bin/gcc
      CXX: /usr/bin/g++
    steps:
      - checkout
      - run:
          command: ./b --build-32-bit --cfg Debug -v

  build-gcc-32-release:
    docker:
      - image: charlesnicholson/circleci-images:latest
    environment:
      CC: /usr/bin/gcc
      CXX: /usr/bin/g++
    steps:
      - checkout
      - run:
          command: ./b --build-32-bit --cfg Release -v

  build-clang-debug:
    docker:
      - image: charlesnicholson/circleci-images:latest
    environment:
      CC: /usr/bin/clang
      CXX: /usr/bin/clang++
    steps:
      - checkout
      - run:
          command: ./b --cfg Debug -v

  build-clang-release:
    docker:
      - image: charlesnicholson/circleci-images:latest
    environment:
      CC: /usr/bin/clang
      CXX: /usr/bin/clang++
    steps:
      - checkout
      - run:
          command: ./b --cfg Release -v

workflows:
  submit-gate:
    jobs:
      - build-gcc-debug
      - build-gcc-release
      - build-clang-debug
      - build-clang-release
